/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rennspiel;

/**
 *
 * @author bbsuser
 */
public class Autorennspiel extends javax.swing.JFrame {

    /**
     * Creates new form Autorennspiel
     */
    public Autorennspiel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _btnWeiterSpA = new javax.swing.JButton();
        _btnBremsenSpA = new javax.swing.JButton();
        _btnBeschleunigenSpA = new javax.swing.JButton();
        _btnWeiterSpB = new javax.swing.JButton();
        _btnBremsenSpB = new javax.swing.JButton();
        _btnBeschleunigenSpB = new javax.swing.JButton();
        _lblSpielerA = new javax.swing.JLabel();
        _lblSpielerB = new javax.swing.JLabel();
        _lblWetter = new javax.swing.JLabel();
        _lblGeschwindigkeitSpA = new javax.swing.JLabel();
        _lblGeschwindigkeitSpB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _btnWeiterSpA.setText("Weiter");
        _btnWeiterSpA.setFocusPainted(false);
        _btnWeiterSpA.setPreferredSize(new java.awt.Dimension(101, 23));
        _btnWeiterSpA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnWeiterSpAActionPerformed(evt);
            }
        });

        _btnBremsenSpA.setText("Bremsen");
        _btnBremsenSpA.setFocusPainted(false);
        _btnBremsenSpA.setMaximumSize(new java.awt.Dimension(101, 23));
        _btnBremsenSpA.setMinimumSize(new java.awt.Dimension(101, 23));
        _btnBremsenSpA.setPreferredSize(new java.awt.Dimension(101, 23));

        _btnBeschleunigenSpA.setText("Beschelunigen");
        _btnBeschleunigenSpA.setFocusPainted(false);

        _btnWeiterSpB.setText("Weiter");
        _btnWeiterSpB.setFocusPainted(false);
        _btnWeiterSpB.setPreferredSize(new java.awt.Dimension(101, 23));
        _btnWeiterSpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnWeiterSpBActionPerformed(evt);
            }
        });

        _btnBremsenSpB.setText("Bremsen");
        _btnBremsenSpB.setFocusPainted(false);
        _btnBremsenSpB.setMaximumSize(new java.awt.Dimension(101, 23));
        _btnBremsenSpB.setMinimumSize(new java.awt.Dimension(101, 23));
        _btnBremsenSpB.setPreferredSize(new java.awt.Dimension(101, 23));

        _btnBeschleunigenSpB.setText("Beschelunigen");
        _btnBeschleunigenSpB.setFocusPainted(false);

        _lblSpielerA.setForeground(new java.awt.Color(0, 0, 255));
        _lblSpielerA.setText("Spieler A");

        _lblSpielerB.setForeground(new java.awt.Color(0, 0, 255));
        _lblSpielerB.setText("Spieler B");

        _lblWetter.setForeground(new java.awt.Color(0, 255, 51));
        _lblWetter.setText("Wetter");

        _lblGeschwindigkeitSpA.setForeground(new java.awt.Color(255, 0, 51));
        _lblGeschwindigkeitSpA.setText("Geschwindigkeit");

        _lblGeschwindigkeitSpB.setForeground(new java.awt.Color(255, 0, 51));
        _lblGeschwindigkeitSpB.setText("Geschwindigkeit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(_lblWetter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_btnWeiterSpA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_btnBremsenSpA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_btnBeschleunigenSpA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_btnWeiterSpB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_btnBremsenSpB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_btnBeschleunigenSpB)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_lblSpielerA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_lblSpielerB))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(_lblGeschwindigkeitSpB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_lblGeschwindigkeitSpA)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(_lblWetter)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lblSpielerA)
                    .addComponent(_lblSpielerB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lblGeschwindigkeitSpA)
                    .addComponent(_lblGeschwindigkeitSpB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_btnWeiterSpB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_btnBremsenSpB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_btnBeschleunigenSpB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_btnWeiterSpA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_btnBremsenSpA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_btnBeschleunigenSpA)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btnWeiterSpAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnWeiterSpAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__btnWeiterSpAActionPerformed

    private void _btnWeiterSpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnWeiterSpBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__btnWeiterSpBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autorennspiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autorennspiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autorennspiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autorennspiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autorennspiel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnBeschleunigenSpA;
    private javax.swing.JButton _btnBeschleunigenSpB;
    private javax.swing.JButton _btnBremsenSpA;
    private javax.swing.JButton _btnBremsenSpB;
    private javax.swing.JButton _btnWeiterSpA;
    private javax.swing.JButton _btnWeiterSpB;
    private javax.swing.JLabel _lblGeschwindigkeitSpA;
    private javax.swing.JLabel _lblGeschwindigkeitSpB;
    private javax.swing.JLabel _lblSpielerA;
    private javax.swing.JLabel _lblSpielerB;
    private javax.swing.JLabel _lblWetter;
    // End of variables declaration//GEN-END:variables
}
